call plug#begin('~/.vim-plug')
Plug 'w0rp/ale'
Plug 'scrooloose/nerdTree'
Plug 'junegunn/limelight.vim'
Plug 'tomtom/tcomment_vim'
Plug 'vim-scripts/bufexplorer.zip'
Plug 'junegunn/goyo.vim'
Plug 'vim-scripts/grep.vim'
Plug 'chriskempson/base16-vim'
Plug 'yggdroot/indentline'
Plug 'vim-scripts/mru.vim'
Plug 'tpope/vim-vinegar'
Plug 'konfekt/fastfold'
Plug 'tmhedberg/simpylfold'
Plug 'andrewradev/splitjoin.vim'
Plug 'sirver/ultisnips'
Plug 'honza/vim-snippets'
" Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-surround'
Plug 'dhruvasagar/vim-table-mode'
" Plug 'christoomey/vim-tmux-navigator'
Plug 'maxbrunsfeld/vim-yankstack'
Plug 'amix/vim-zenroom2'
Plug 'jiangmiao/auto-pairs'
Plug 'ludovicchabant/vim-gutentags'
Plug 'majutsushi/tagbar'
Plug 'roxma/nvim-yarp'
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
Plug 'roxma/nvim-yarp'
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'rbgrouleff/bclose.vim'
Plug 'kien/rainbow_parentheses.vim'
Plug 'tpope/vim-repeat'
Plug 'bfredl/nvim-ipy'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
" Plug 'python-mode/python-mode', { 'branch': 'develop' }
" Plug 'Chiel92/vim-autoformat'
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-eunuch'
Plug 'vim-scripts/LanguageTool'
Plug 'easymotion/vim-easymotion'
Plug 'haya14busa/incsearch.vim'
Plug 'haya14busa/incsearch-easymotion.vim'
Plug 'terryma/vim-multiple-cursors'
Plug 'andymass/vim-matchup'
Plug 'ron89/thesaurus_query.vim'
Plug 'mike-hearn/base16-vim-lightline'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

Plug 'gmoe/vim-faust'
Plug 'vhda/verilog_systemverilog.vim'
Plug 'sophacles/vim-processing'
Plug 'supercollider/scvim'
Plug 'tidalcycles/vim-tidal', {'branch': '1.0.0-pre'}
Plug 'lervag/vimtex'
Plug 'jalvesaq/nvim-r'
call plug#end()
source ~/.vim/vimrcs/basic.vim
source ~/.vim/vimrcs/filetypes.vim
source ~/.vim/vimrcs/extended.vim
source ~/.vim/vimrcs/plugins_config.vim
source ~/.vim/vimrcs/extra_configs.vim
